# Development Docker Compose with Hot Reload

services:
  blog-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/tmp  # Exclude tmp directory from mounting
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - LOG_LEVEL=debug
      - DEV_MODE=true
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add PostgreSQL for future use
  # postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_DB: blog_db
  #     POSTGRES_USER: blog_user
  #     POSTGRES_PASSWORD: blog_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U blog_user -d blog_db"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # Optional: Add Redis for future use
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

# volumes:
#   postgres_data:

networks:
  default:
    name: blog-api-dev